# Generated by Django 6.0.3 on 2026-03-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_issue_issue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='capanicus_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='component_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_message',
            field=models.TextField(default='No message provided'),
        ),
        migrations.AddField(
            model_name='issue',
            name='screenshot_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='mcm_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
