# Generated by Django 6.0.3 on 2026-04-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_issue_capanicus_comment_issue_component_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='sheet_name',
            field=models.CharField(default='Default', max_length=255),
        ),
    ]
