# Generated by Django 6.0.3 on 2026-04-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_issue_sheet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='planned_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='resource',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='utilized_hours',
            field=models.FloatField(default=0),
        ),
    ]
