# Generated by Django 6.0.3 on 2026-04-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_issue_planned_hours_issue_priority_issue_resource_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='csvupload',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='row_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status'], name='dashboard_i_status_a26b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['issue_id'], name='dashboard_i_issue_i_eef008_idx'),
        ),
    ]
