# Generated by Django 6.0.3 on 2026-04-03 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_issue_options_csvupload_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('connection_type', models.CharField(choices=[('google_sheets', 'Google Sheets'), ('excel_online', 'Excel Online'), ('upload', 'File Upload')], max_length=20)),
                ('sheet_url', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('sheet_id', models.CharField(blank=True, max_length=200, null=True)),
                ('sheet_name', models.CharField(default='Sheet1', max_length=100)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.sheetconnection'),
        ),
    ]
