# Generated by Django 6.0.3 on 2026-04-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_sheetconnection_issue_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetconnection',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
