# Generated by Django 6.0.3 on 2026-04-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_sheetconnection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetconnection',
            name='sheet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
