# Generated by Django 6.0.3 on 2026-04-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_sheetconnection_sheet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetconnection',
            name='column_mapping',
            field=models.JSONField(blank=True, help_text='User-selected column mapping for this connection', null=True),
        ),
    ]
